### ISSUE TITLE
Possible bug when tags differ across multiple .pbf files

### ISSUE THREAD

**Issue by zackAemmer** [kraina-ai/quackosm#42]
Thanks for providing these awesome libraries!

Ran into a possible bug that seems to happen only when concatenating features loaded from geometry that spans multiple .pbf files. The issue arises when a tag is found in one file but not the other; the schemas end up not matching when calling pa.concat_tables() in PbfFileReader._drop_duplicates_features_in_pyarrow_table()

Here is a specific example for a geometry that spans two pbf files when downloaded from geofabrik, one file has military: "airfield" and the other does not:

```
import geopandas as gpd
from shapely import Polygon
from srai.constants import WGS84_CRS
from quackosm import PbfFileReader
from quackosm.osm_extracts import OsmExtractSource

min_x, max_x, min_y, max_y = (-85.904275,-85.502994,38.056361,38.383253)
geo = Polygon((
    (min_x, min_y),
    (min_x, max_y),
    (max_x, max_y),
    (max_x, min_y),
    (min_x, min_y)
))
area = gpd.GeoDataFrame(
    {'region_id': ["Kentucky-Indiana"], 'geometry': [geo]},
    crs=WGS84_CRS
)
tags = {
    'military': ['airfield'],
    'leisure': ['park']
}
pbf_reader = PbfFileReader(
    tags_filter=tags,
    geometry_filter=area.unary_union,
    osm_extract_source=OsmExtractSource("geofabrik"),
)
features_gdf = pbf_reader.get_features_gdf_from_geometry(explode_tags=True)

# pyarrow.lib.ArrowInvalid: Schema at index 1 was different: 
# feature_id: string
# military: string
# leisure: string
# geometry: extension<geoarrow.wkb<WkbType>>
# vs
# feature_id: string
# leisure: string

print(pd.unique(features_gdf['military']))
print(pd.unique(features_gdf['leisure']))
```

I changed the concatenation in PbfFileReader to:
```joined_parquet_table: pa.Table = pa.concat_tables(parquet_tables, promote_options="default")```
which seemed to fix my particular case, but I'm not sure if this breaks other intended functionality.

**Comment by RaczeQ** [comment]
Thank you @zackAemmer for reporting this issue. I can confirm that this is not working as intended.
I didn't stumble across it when testing the library. I've checked the pyarrow documentation and your proposed solution fixes the problem, so I've added you as a co-author of the fix commit.

I'll now run the patch release to 0.4.3 and it should be done in a few hours.
